name: B_KONAMI
sha1: 14829c61f976b261e0b89ee9f967f1be70a54fc6
options:
  basename: B_KONAMI.BIN
  target_path: assets/1ST/B_KONAMI.BIN
  base_path: ..
  platform: psx
  compiler: GCC

  asm_path: asm/b_konami
  asset_path: assets/b_konami
  src_path: src/b_konami

  ld_script_path: linker/B_KONAMI.BIN.ld

  find_file_boundaries: False
  gp_value: 0x80022BB0

  use_legacy_include_asm: False

  section_order: [".rodata", ".text", ".data", ".bss"]

  symbol_addrs_path:
    - meta/symbol_addresses.main.txt
    - meta/symbol_addresses.bodyprog.txt
    - meta/symbol_addresses.b_konami.txt
  reloc_addrs_path: meta/reloc_addrs.b_konami.txt
  undefined_funcs_auto_path: meta/undefined_functions_auto.b_konami.txt
  undefined_syms_auto_path: meta/undefined_symbols_auto.b_konami.txt

  extensions_path: tools/splat_ext

  subalign: 4

  string_encoding: ASCII
  data_string_encoding: ASCII
  rodata_string_guesser_level: 2
  data_string_guesser_level: 2
rom:
  path: rom/image
  extraction_path: rom
segments:
  - name: b_konami
    type: code
    start: 0
    vram: 0x800C9578
    subalign: 4
    align: 4
    subsegments:
      - [0x0, rodata]
      - [0x34, c, overlay_b_konami]
      - [0xF78, data, overlay_b_konami] # padding at end?
  - [0x1000]
